services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: easy_budget_app
    restart: always
    # Load all environment variables directly from the .env file
    env_file:
      - /home/hosting/env/easy_budget_be.env
    # Connect the app container to the external network shared with the Redis container
    networks:
      - shared-network
    # Run database migrations first, then start the server
    command: sh -c "npm run start"

networks:
  shared-network:
    external: true
    name: shared-network
